name: windows_single_launch
description: "Launch Windows applications from a single instance. Brings the current instance to the front on each launch."
version: 0.0.5

platforms:
  windows:

repository: https://github.com/hasan-bulut/windows_single_launch
issue_tracker: https://github.com/hasan-bulut/windows_single_launch/issues


environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: WindowsSingleLaunchPluginCApi
